<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Lihtar.Application\Lihtar.Application.csproj" />
		<ProjectReference Include="..\Lihtar.Infrastructure\Lihtar.Infrastructure.csproj" />
	</ItemGroup>

</Project>
